<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

/**
 * Vite Integration Configuration
 *
 * Controls how CodeIgniter discovers and serves Vite-built assets.
 * Entry access rules are defined in vite.config.ts and compiled
 * into ci-manifest.json at build time — this config tells the PHP
 * side where to find that manifest and how to serve files.
 */
class Vite extends BaseConfig
{
    /**
     * Directory where Vite writes compiled assets.
     * Relative to WRITEPATH or an absolute path.
     */
    public string $buildPath = WRITEPATH . 'app';

    /**
     * Name of the CI manifest generated by vite-plugin-codeigniter.
     */
    public string $manifestFile = 'ci-manifest.json';

    /**
     * Name of the hot-reload marker file written by the dev server.
     */
    public string $hotFile = 'hot';

    /**
     * URL prefix used when generating asset URLs.
     * Must match the route registered for AssetController::serve().
     */
    public string $assetUrlPrefix = '/build';

    /**
     * Whether to use the Vite dev server even when the hot file is absent.
     * Useful for debugging; normally left false.
     */
    public bool $forceDevMode = false;

    /**
     * Vite dev server URL fallback (used when hot file is missing
     * and forceDevMode is true).
     */
    public string $devServerUrl = 'http://localhost:5173';

    /**
     * Backend API route prefix.
     * React frontend calls fetch('/api/...') — in dev mode Vite
     * proxies these to the CI4 server automatically.
     */
    public string $apiPrefix = '/api';

    /**
     * Cache the parsed manifest in memory for the duration of the request.
     */
    public bool $cacheManifest = true;

    /**
     * Map of entry names → view files.
     * Used by the spark vite:entries command for discovery.
     * Controllers can also reference entries by name via ci_vite().
     */
    public array $entryViews = [
        'index'     => 'react/index',
        'protected' => 'react/protected',
    ];
}
